# mise configuration file
# This replaces asdf (.tool-versions) and direnv (.envrc) functionality

[tools]
python = "3.13.7"
uv = "latest"

# Automatically activate uv-managed virtual environment
[env]
_.python.venv = { path = ".venv", create = true }
VIRTUAL_ENV = "{{config_root}}/.venv"

# Task definitions
[tasks.test]
description = "Run tests with pytest"
run = "pytest tests/ -v"

[tasks."test:coverage"]
description = "Run tests with coverage report"
run = "coverage run -m pytest tests/ && coverage report -m"

[tasks.lint]
description = "Check code style with ruff"
run = "ruff check ."

[tasks."lint-fix"]
description = "Fix auto-fixable linting issues with ruff"
run = "ruff check --fix ."

[tasks.format]
description = "Format code with ruff"
run = "ruff format ."

[tasks."format:check"]
description = "Check if code is formatted without making changes"
run = "ruff format --check ."

[tasks.typecheck]
description = "Type check with mypy"
run = "mypy gilded_rose.py gilded_rose_item.py texttest_fixture.py tests/"

[tasks.install]
description = "Install dependencies with uv"
run = "uv pip install -e .[dev]"

[tasks.sync]
description = "Sync dependencies with uv"
run = "uv sync"

[tasks.check]
description = "Run all checks (format, lint, typecheck, test)"
run = [
  "mise run format:check",
  "mise run lint",
  "mise run typecheck",
  "mise run test"
]
depends = ["format:check", "lint", "typecheck", "test"]
